"""
Rebuilds catalogs.js from the sofatutor .xlsx catalog spreadsheets.

    python tools/build_catalogs.py                 reads the folder above website/
    python tools/build_catalogs.py path/to/folder  reads a different folder

Needs openpyxl:  pip install openpyxl

Every .xlsx file in the folder becomes one built-in catalog. The spreadsheet
must follow the sofatutor layout:

    column A   Datum          ignored
    column B   Video-Titel    bold cells are topic headings, plain cells are videos
    column C   (tick box)     ignored

The sheet name becomes the catalog's label, minus a trailing "Katalog", and the
label's first word becomes its subject ("Mathematik Klasse 8 Katalog" gives
label "Mathematik Klasse 8" and subject "Mathematik"). The subject is what
SCHEDULE in js/config.js matches against.

Changing a catalog's subject changes its id, which disconnects it from any
progress already recorded against the old id.
"""

import glob
import json
import os
import sys

import openpyxl

WEBSITE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SOURCE_DIR = os.path.dirname(WEBSITE_DIR)
OUTPUT_FILE = os.path.join(WEBSITE_DIR, "catalogs.js")


def read_catalog(path):
    """Turns one spreadsheet into a catalog dictionary."""
    sheet = openpyxl.load_workbook(path).worksheets[0]

    label = sheet.title.removesuffix("Katalog").strip()
    subject = label.split()[0]

    videos = []
    topic = ""
    for row in sheet.iter_rows(min_row=2):  # row 1 is the header
        cell = row[1]  # column B
        if cell.value in (None, ""):
            continue

        title = str(cell.value).strip()
        if cell.font and cell.font.bold:
            topic = title  # a heading; the videos below it belong to it
        else:
            videos.append({"title": title, "topic": topic})

    return {
        "id": "builtin:" + subject.lower(),
        "subject": subject,
        "label": label,
        "source": "built-in",
        "videos": videos,
    }


def main():
    source_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE_DIR
    paths = sorted(glob.glob(os.path.join(source_dir, "*.xlsx")))
    if not paths:
        sys.exit(f"No .xlsx files found in {source_dir}")

    catalogs = [read_catalog(path) for path in paths]
    for catalog in catalogs:
        print(f"  {catalog['label']}: {len(catalog['videos'])} videos")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
        out.write("// Generated by tools/build_catalogs.py. Edit the spreadsheets and\n")
        out.write("// re-run that script instead of editing this file by hand.\n")
        out.write("window.BUILTIN_CATALOGS = ")
        json.dump(catalogs, out, ensure_ascii=False)
        out.write(";\n")

    total = sum(len(c["videos"]) for c in catalogs)
    print(f"Wrote {len(catalogs)} catalogs ({total} videos) to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
